baseURL = "/"
title = "Kinh Nghiệm Số"
author = "Khoi Le"
defaultContentLanguage = "vi"
enableInlineShortcodes = true
enableRobotsTXT = true
timeout = 30000

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-1234567890"

[taxonomies]
category = "categories"
tag = "tags"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[markup]
  [markup.highlight]
    codeFences = false
    noClasses = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false