# toml-docs-start lang-main
[vi]
    languageName = "Tiếng Việt"
    contentDir = "content"
    weight = 1
# toml-docs-end lang-main
# toml-docs-start lang-param
    [vi.params.head]
        tagline = "Kinh Nghiệm Hay, Mẹo Vặt"
    [vi.params.social]
        title = "Kết Nối với Chúng Tôi"
        caption = ""
    [vi.params.footer]
        license = " Licensed under Creative Commons "
# toml-docs-end lang-param


