# toml-docs-start lang-main
[vi]
    languageName = "Tiếng Việt"
    contentDir = "content"
    weight = 1
# toml-docs-end lang-main
# toml-docs-start lang-param
    [vi.params.head]
        tagline = "Uy Tín Chất Lượng"
    [vi.params.social]
        title = "Follow us"
        caption = "Hotline / zalo : 0966171436"
# toml-docs-end lang-param
    [vi.params.sections.posts]
        reference = "Xem Tất Cả Bài Viết"
        [vi.params.sections.tre-tho]
        reference = "Xem Tất Cả Bài Viết"

