# Base color of the website.
base_color = "bg-gray-800"

# Logo Configuration
logo = "/favicon/logo.svg"
logo_alt = "Kinh Nghiệm Hay"
logo_width = "auto"
logo_height = "30px"

#Site description
description = "Kinh Nghiệm Số"

# The number of articles to be displayed on a single page.
paginator_pages = "12"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "false"

# Number of tags to be displayed.
tagsLimit = 20

# Dark mode by default : dark
# Light mode by default : light
darkmode = "light"

  [ad]
    # Google AdSense
    # ex. ca-pub-0000000000000000
    googleAdSense = ""

    # ex. 000000000
    adslot = ""

    # Placement of ads
    postTop = false
    postBottom = false

  [post]
    # Show thumbnails
    thumbnail = true

    # Disable the "NO IMAGE" image.
    noimage = true

    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "lg:h-44"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "lg:w-auto"

    # Number of characters in description
    description = "130"

  [widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = ["search", "category", "tags", "recent"]