[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Thẻ Thơ"
  pageRef = "/tre-tho/"
  weight = 20

[[main]]
  name = "Kỹ Năng"
  pageRef = "/skills/"
  weight = 30

[[main]]
  name = "Trẻ Tự Kỷ"
  pageRef = "/book/"
  weight = 40

[[main]]
  name = "marketing"
  pageRef = "/marketing/"
  weight = 40

[[main]]
  name = "PC"
  pageRef = "/pc/"
  weight = 40

[[main]]
  name = "Liên Hệ"
  pageRef = "/lien-he/"
  weight = 50

