[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Nuôi dạy Con"
  pageRef = "/tre-tho/"
  weight = 20

[[main]]
  name = "PC"
  pageRef = "/pc/"
  weight = 30

[[main]]
  name = "Liên Hệ"
  pageRef = "/lien-he/"
  weight = 80

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com"
  weight = 20

[[social]]
  name = "X"
  pre = "fab fa-square-x-twitter"
  url = "https://x.com/"
  weight = 30

